name: Debug Structure
on: [workflow_dispatch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check structure
        run: |
          docker run -it --rm -v $(pwd):/source itdoginfo/openwrt-sdk-ipk:24.10.3 bash -c "
            echo '=== SDK structure ==='
            ls -la /builder/package/
            echo '=== Copying files ==='
            cp -r /source /builder/package/parentcontrol
            echo '=== Copied structure ==='
            find /builder/package/parentcontrol -type f
            echo '=== Available packages ==='
            find /builder/package -name 'Makefile' | head -10
          "