name: Build Parental Control
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug - Show project structure
        run: |
          echo "=== Project Structure ==="
          find . -type f -name "*.sh" -o -name "*.lua" -o -name "config" | head -20
          echo "=== Directories ==="
          ls -la
          echo "=== package/ contents ==="
          ls -la package/ || echo "No package directory"
          echo "=== parentcontrol/ contents ==="
          ls -la package/parentcontrol/ || echo "No parentcontrol directory"
          
      - name: Build with Docker and extract IPK
        run: |
          # Собираем в Docker
          docker build -f Dockerfile-ipk -t parentcontrol-builder .
          
          # Создаем контейнер и копируем ТОЛЬКО IPK
          docker create --name builder parentcontrol-builder
          docker cp builder:/builder/bin/packages/ ./ipk-files/
          docker rm builder
          
          echo "=== IPK Files ==="
          find ./ipk-files -name "parentcontrol*.ipk" -exec cp {} . \; -exec ls -la {} \;
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: parentcontrol*.ipk