name: Build Parental Control
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  preparation:
    name: Setup build version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          VERSION=$(git describe --tags --exact-match 2>/dev/null || echo "0.$(date +%d%m%Y)")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  build:
    name: Build IPK package
    runs-on: ubuntu-latest
    needs: preparation
    
    steps:
      - uses: actions/checkout@v4

      - name: Build IPK
        uses: docker/build-push-action@v6.18.0
        with:
          file: ./Dockerfile-ipk
          context: .
          tags: parentcontrol:ci-ipk
          build-args: |
            PARENTCONTROL_VERSION=${{ needs.preparation.outputs.version }}
          push: false

      - name: Create Docker container
        run: docker create --name ipk-builder parentcontrol:ci-ipk

      - name: Copy files directly
        run: |
          mkdir -p ./bin/ipk
          echo "=== Copying from luci ==="
          docker cp ipk-builder:/builder/bin/packages/x86_64/luci/. ./bin/ipk/
          echo "=== Copied files ==="
          ls -la ./bin/ipk/ | grep parentcontrol || echo "No parentcontrol files found"

      - name: Check what was copied
        run: |
          echo "=== All files in bin/ipk ==="
          ls -la ./bin/ipk/
          echo "=== Parentcontrol files ==="
          find ./bin/ipk/ -name "*parentcontrol*" -type f

      - name: Fix naming
        run: |
          for f in ./bin/ipk/*.ipk; do
            [ -e "$f" ] || continue
            base=$(basename "$f")
            newname=$(echo "$base" | sed 's/_/-/g')
            mv "$f" "./bin/ipk/$newname"
            echo "Renamed: $base -> $newname"
          done

      - name: Analyze IPK content
        run: |
          echo "=== Analyzing luci-app-parentcontrol IPK ==="
          tar -tzf ./bin/ipk/luci-app-parentcontrol-*.ipk
          echo "=== File size breakdown ==="
          tar -xzf ./bin/ipk/luci-app-parentcontrol-*.ipk --to-stdout data.tar.gz | tar -tzv | head -20
          echo "=== Control files ==="
          tar -xzf ./bin/ipk/luci-app-parentcontrol-*.ipk --to-stdout control.tar.gz | tar -tzv

      - name: Filter files
        run: |
          VERSION="${{ needs.preparation.outputs.version }}"
          mkdir -p ./filtered-bin/ipk
          echo "=== Files before filtering ==="
          ls -la ./bin/ipk/ | grep parentcontrol || echo "No parentcontrol files to filter"
          cp ./bin/ipk/luci-app-parentcontrol-*.ipk ./filtered-bin/ipk/ 2>/dev/null || echo "No main package"
          cp ./bin/ipk/luci-i18n-parentcontrol-*.ipk ./filtered-bin/ipk/ 2>/dev/null || echo "No translation package"
          echo "=== Files after filtering ==="
          ls -la ./filtered-bin/ipk/ || echo "No filtered files"

      - name: Remove Docker container
        run: docker rm ipk-builder

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: filtered-bin/ipk/*.ipk