name: Build Parental Control
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Docker and extract IPK
        run: |
          # Собираем в Docker
          docker build -f Dockerfile-ipk -t parentcontrol-builder .
          
          # Создаем контейнер и копируем ТОЛЬКО IPK
          docker create --name builder parentcontrol-builder
          docker cp builder:/builder/bin/packages/ ./ipk-files/
          docker rm builder
          
          echo "=== IPK Files ==="
          find ./ipk-files -name "parentcontrol*.ipk" -exec cp {} . \; -exec ls -la {} \;
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: parentcontrol*.ipk