name: Build Parental Control
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  preparation:
    name: Setup build version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          VERSION=$(git describe --tags --exact-match 2>/dev/null | sed 's/^v//' || echo "0.$(date +%d%m%Y)")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  build:
    name: Build IPK package
    runs-on: ubuntu-latest
    needs: preparation
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build IPK
        run: |
          docker build -f Dockerfile-ipk -t parentcontrol-builder \
            --build-arg PARENTCONTROL_VERSION=${{ needs.preparation.outputs.version }} .
          
      - name: Create Docker container
        run: docker create --name ipk-builder parentcontrol-builder
          
      - name: Copy IPK files
        run: |
          mkdir -p ./bin/ipk
          docker cp ipk-builder:/builder/bin/packages/x86_64/luci/. ./bin/ipk/
          
      - name: Fix naming
        run: |
          for f in ./bin/ipk/*.ipk; do
            [ -e "$f" ] || continue
            base=$(basename "$f")
            newname=$(echo "$base" | sed 's/_/-/g')
            mv "$f" "./bin/ipk/$newname"
          done
          
      - name: Remove Docker container
        run: docker rm ipk-builder
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/ipk/luci-app-parentcontrol*.ipk